site_name: Yourdrs Help
site_description: Documentation for Yourdrs Help
site_author: Yourdrs Team
site_url: https://yourdrs.com/help
nav:
  - Home: index.md
  - Office Dashboard:
      - Overview: Office-Dashboard/Overview.md
      - Features: Office-Dashboard/features.md
theme: readthedocs
